openapi: 3.0.3
info:
  title: Institutions Search API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /institutions/search:
    get:
      tags:
        - Institution
      summary: Search for institutions
      description: Returns a JSON response containing details for institutions that match the query parameters, up to a maximum of ten institutions per query
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: Search query to filter institutions.
        - name: country_codes
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
            minItems: 1
          description: Specify which country or countries to include institutions from. Possible values include US, GB, ES, NL, FR, IE, CA, DE, IT, PL, DK, NO, SE, EE, LT, LV, PT, BE.
        - name: products
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
          description: Filter the Institutions based on whether they support all products listed in products. Possible values include assets, auth, balance, employment, identity, income_verification, investments, liabilities, identity_verification, payment_initiation, standing_orders, transactions, transfer.
        - name: options
          in: query
          required: false
          schema:
            type: string
            default: '{"oauth":false,"include_optional_metadata":false,"include_auth_metadata":false,"include_payment_initiation_metadata":false}'
          description: |
            An optional stringified object to filter /institutions/search results.
            Example:
            ```json
            {
              "oauth": true,
              "include_optional_metadata": true,
              "include_auth_metadata": false,
              "include_payment_initiation_metadata": false,
              "payment_initiation": {
                "payment_id": "some_payment_id",
                "consent_id": "some_consent_id"
              }
            }
            ```
      responses:
        "200":
          description: Successful response with a list of institutions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  institutions:
                    type: array
                    items:
                      type: object
                      properties:
                        country_codes:
                          type: array
                          items:
                            type: string
                        dtc_numbers:
                          type: array
                          items:
                            type: string
                        institution_id:
                          type: string
                        name:
                          type: string
                        oauth:
                          type: boolean
                        products:
                          type: array
                          items:
                            type: string
                        routing_numbers:
                          type: array
                          items:
                            type: string
                  request_id:
                    type: string
        "400":
          description: Bad Request - Invalid country_codes parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
